name: swap_zone
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-166.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_screenutil: ^5.8.4
  email_validator: ^2.1.17
  shared_preferences: ^2.2.0
  toast: ^0.3.0
  image_picker: ^1.0.0
  easy_localization: ^3.0.2
  flutter_phoenix: ^1.1.1
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/ar-SA.json
    - assets/translations/en-US.json

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700